
name: Weekly refresh
on:
  schedule:
    - cron: "0 11 * * 1"
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup service account credentials
        env:
          GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
        run: |
          # Write credentials to secure temp location
          echo "$GOOGLE_CREDENTIALS_B64" | base64 -d > $RUNNER_TEMP/sa.json
          # Set restrictive permissions
          chmod 600 $RUNNER_TEMP/sa.json
          # Verify the file was created securely
          ls -la $RUNNER_TEMP/sa.json
      - name: Run pipeline
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/sa.json
          SHEET_ID: ${{ secrets.SHEET_ID }}
          DAYS_LOOKBACK: "90"
          WEEKLY_BASELINE_WEEKS: "13"
          ENABLE_PERMITS: "true"
          ENABLE_CTA: "true"
        run: python -m src.main
